FROM openjdk:12-alpine3.8
WORKDIR /var/lib/jenkins/workspace/demo-android
COPY target/selenium-test.jar selenium-test.jar
COPY target/selenium-test-tests.jar selenium-test-tests.jar
COPY target/libs libs
COPY sample-test.testng.xml testng.xml
ENTRYPOINT java -cp selenium-test.jar:selenium-test-tests.jar:libs/* -DHUB_HOST=$HUB_HOST org.testng.TestNG

